config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'welcome', to: 'welcome#index'

  get 'list', to: 'list#index'
  get 'list/pokemon/:name', to: 'list#pokemon', as: 'list_pokemon'
  get 'list/import', to: 'list#import'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  self.table_name = 'pokemondb'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
    @list = Pokemon.all
  end

  def pokemon
    @name = params[:name]
    @result = Pokemon.find_by name: @name
  end

  def import
    url = 'https://pokeapi.co/api/v2/pokemon?limit=151&offset=0'
    response = RestClient.get url
    result = JSON.parse response.to_str
    @list = []

    result['results'].each do |character|
      response = RestClient.get character['url']
      temp = JSON.parse response.to_str

      Pokemon.create({
                       name: temp['forms'][0]['name'],
                       image: temp['sprites']['versions']['generation-v']['black-white']['animated']['front_default'],
                       abilities: temp['abilities'].map { |ability| ability['ability']['name'] },
                       pokemon_type: temp['types'][0]['type']['name']
                     })
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list/index.html.erb
<table table style="width:100%" class = "table table-striped table-bordered">
  <thead>
    <tr>
      <th>Image<b></th>
      <th>Name<b></th>
      <th>Type<b></th>
      <th>Abilities<b></th>
    </tr>
  </thead>
  <tbody>
    <% @list.each do |name| %>
      <tr>
        <td>
          <%= link_to ("<img src='#{name[:image]}' >").html_safe , list_pokemon_url(name[:name]) %>
        </td>
        <td>
          <%= name[:name] %>
        </td>
        <td>
          <%= name[:pokemon_type] %>
        </td>
        <td>
          <%= name[:abilities] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/list/pokemon.html.erb
<h1>
  <%= @result.name  %>
</h1>
<img src= <%= @result.image %>>
<table table style="width:100%" class = "table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name<b></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>
          <%= @result.abilities %>
        </td>
      </tr>
  </tbody>
</table>
<table table style="width:100%" class = "table table-striped  table-bordered">
  <thead>
    <tr>
    <th>Type<b></th>
  </tr>
</thead>
  <tbody>
      <tr>
        <td>
          <%= @result.pokemon_type %>
        </td>
      </tr>
  </tbody>
</table>